import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useSession} from "next-auth/react"
import Link from 'next/link'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  

  const {data: session} = useSession();

  return (
    <>
      <Head>
  <title>SmashBell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link />
      </Head>
      
      <main>
        
          <div className="carousel absolute w-full">
            <Image src={require('../../public/./Images/Demon.jpg')} alt="Icon" className="absolute top 0 h-full w-full bg-cover bg-center" />
                  <div id="slide1" className="carousel-item relative w-full">
                    <div className="hero min-h-screen">
                      <div className="hero-overlay bg-opacity-60"></div>
                        <div className="hero-content text-center text-neutral-content">
                          <div className="max-w-md">
                            <h1 className="mb-5 text-5xl font-bold">Smash Bell</h1>
                            <p className="mb-5">Vive cada evento en la pagina más grande de noticias de Smash, crea tu cuenta ahora! 
                            </p>
                            <Link href="/login"  className="btn btn-primary">Login</Link> 
                          </div>
                        <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
                          <a href="#slide4" className="btn btn-circle">❮</a> 
                          <a href="#slide2" className="btn btn-circle">❯</a>
                  </div>
                </div>
              </div>
            </div> 
            <div id="slide2" className="carousel-item relative w-full">
            <Image src={require('../../public/./Images/skeleton.jpg')} alt="Icon" className=" top 0 h-full w-full bg-cover bg-center" />
              <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
                <a href="#slide1" className="btn btn-circle">❮</a> 
                <a href="#slide3" className="btn btn-circle">❯</a>
              </div>
            </div> 
            <div id="slide3" className="carousel-item relative w-full">
            <Image src={require('../../public/./Images/Dva.jpg')} alt="Icon" className=" top 0 h-full w-full bg-cover bg-center" />
              <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
                <a href="#slide2" className="btn btn-circle">❮</a> 
                <a href="#slide4" className="btn btn-circle">❯</a>
              </div>
            </div> 
            <div id="slide4" className="carousel-item relative w-full">
            <Image src={require('../../public/./Images/Dva2.jpg')} alt="Icon" className=" top 0 h-full w-full bg-cover bg-center" />
              <div className="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
                <a href="#slide3" className="btn btn-circle">❮</a> 
                <a href="#slide1" className="btn btn-circle">❯</a>
              </div>
            </div>
          </div>
      </main>
    </>
  )
}
